#+STARTUP: indent
#+options: html-style:nil todo:t num:nil html-postamble:t toc:t toc:2 email:t
#+title: Buddhist Studies in UK Universities
#+author: Ilmari Koria
#+email: ilmarikoria@posteo.net
#+date: {{{time(%b %e %Y)}}}

* Introduction
This is a list of UK Universities with academics in Buddhist Studies and related areas providing their research interests. It also includes BA and MA programmes or modules in Buddhist studies, (including modules that have a significant Buddhist content). Also included is an indication of UK course provision for the learning of Sanskrit, Pali and Tibetan languages, as these are largely engaged in for the purpose of research or reading of Buddhist texts. Although not specified separately, where academic staff have the relevant expertise, proposals for doctoral research in Buddhist Studies may be welcomed.

Updates and suggestions can be sent to Ilmari Koria via [[mailto:ilmarikoria@posteo.net][ilmarikoria@posteo.net]].

Last update: _{{{time(%b %e\, %Y)}}}_.

* Table of Contents :noexport:
:properties:
:toc:       :include all :depth 3 :ignore this
:end:
:contents:
- [[#introduction][Introduction]]
- [[#university-list][University List]]
  - [[#cardiff-university][Cardiff University]]
  - [[#durham-university][Durham University]]
  - [[#goldsmiths-university-of-london][Goldsmiths, University of London]]
  - [[#kings-college-london][King's College London]]
  - [[#lancaster-university][Lancaster University]]
  - [[#the-courtauld-institute-of-art][The Courtauld Institute of Art]]
  - [[#university-college-london][University College London]]
  - [[#university-of-aberdeen][University of Aberdeen]]
  - [[#university-of-bristol][University of Bristol]]
  - [[#university-of-cambridge][University of Cambridge]]
  - [[#university-of-chester][University of Chester]]
  - [[#university-of-edinburgh][University of Edinburgh]]
  - [[#university-of-kent][University of Kent]]
  - [[#university-of-leeds][University of Leeds]]
  - [[#university-of-london-school-of-oriental-and-african-studies-soas][University of London, School of Oriental and African Studies (SOAS)]]
  - [[#university-of-manchester][University of Manchester]]
  - [[#university-of-oxford][University of Oxford]]
  - [[#university-of-south-wales][University of South Wales]]
  - [[#university-of-stirling][University of Stirling]]
  - [[#university-of-winchester][University of Winchester]]
:end:

* University List
** Cardiff University
*** People
**** [[https://www.cardiff.ac.uk/history-archaeology-religion][School of History, Archaeology and Religion]]
***** Prof Max Deeg, Professor in Buddhist Studies
- Note: Study Leave 2022/3.
- Research: Buddhist history, particularly the historical connection between India, Central Asia and China; Chinese Buddhist pilgrims.
- Contact: [[mailto:deegm1@cardiff.ac.uk][deegm1@cardiff.ac.uk]]
*** Courses
**** Undergraduate
- /Introduction to Buddhism/ (first year).
- /Buddhism: The first 1000 years/ (a historical overview of that period) [2nd year]
- We also offer Sanskrit as a scriptural language (taught by Dr. Simon Brodbeck).
** Durham University
*** People
**** [[https://www.durham.ac.uk/departments/academic/archaeology/][Department of Archaeology]]
***** Prof Robin Coningham, 2014 UNESCO Chair on Archaeological Ethics and Practice in Cultural Heritage 
- Research: Archaeological Ethics and Practice in Cultural Heritage; Later Prehistory and Early Historic archaeology of Southern Asia (from Iran to Myanmar); Urbanisation; Archaeological visibility of Buddhism; Caste and the development of craft specialisation; Politics, identity and archaeology; International cultural resource management; UNESCO and World Heritage; Post-disaster archaeology; Post-conflict archaeology; Sustainable pilgrimage; Indian Ocean and Arabian Sea Trade
- Contact: [[mailto:r.a.e.coningham@durham.ac.uk][r.a.e.coningham@durham.ac.uk]]
**** [[https://www.durham.ac.uk/departments/academic/philosophy/contact-us/][Department of Philosophy]]
***** Professor Simon P. James, Professor/DEC Chair 
- Research: Environmental philosophy; Existential phenomenology; Buddhist philosophy.
- Contact: [[https://www.durham.ac.uk/departments/academic/philosophy/contact-us/][via departmental contact form]].

** Goldsmiths, University of London
*** People
**** [[https://www.gold.ac.uk/history/][Department of History]]
***** Dr Ronit Yoeli-Tlalim, Reader
- Research: History of Asian Medicine; Interactions between Medicine and Buddhism; Transmission of medical ideas along the Silk-Roads; History of early Tibetan medicine (Dunhuang studies).
- Contact: [[mailto:r.yoeli-tlalim@gold.ac.uk][r.yoeli-tlalim@gold.ac.uk]]
*** Courses
***** Undergraduate
- /Global History of Buddhism/
- /History of Asian Medicine: From Manuscripts to YouTube/
- /Bodies and Drugs: A Global History of Medicine/
- /Medicine on the Silk Roads: Transitions and Transmitions/
** King's College London
*** People
**** [[https://www.kcl.ac.uk/trs][Department of Theology & Religious Studies]]
***** Dr Karen O'Brien-Kop, Lecturer in Modern Asian Religions
- Research: Abhidharma; Yogacara; Meditation; Sanskrit Texts.
- Contact: [[mailto:karen.obrien-kop@kcl.ac.uk][karen.obrien-kop@kcl.ac.uk]]
*** Courses
**** Undergraduate
- /Introduction to Buddhism/
- /Buddhist Ethics/
- /Theravada Buddhism/
**** Graduate Research Reading Group
- /Mind-body philosophies in Asia/
** Lancaster University 
*** People
**** [[https://www.lancaster.ac.uk/ppr/][Department of Politics, Philosophy and Religion]]
***** Prof Chakravarthi Ram-Prasad, Distinguished Professor of Comparative Religion and Philosophy
- Research: Indian (Hindu, Buddhist, Jain) and comparative phenomenology, epistemology, metaphysics, theology, and philosophy of religion; religion, politics and conflict; South Asian religious identities in contemporary Britain; the conceptual sources of modern Hindu life and beliefs.  
- Contact: [[mailto:c.ram-prasad@lancaster.ac.uk][c.ram-prasad@lancaster.ac.uk]]
***** Prof Hiroko Kawanami, Professor of Buddhism and Society
- Research: Gender and Buddhism; dissemination of knowledge and moral values; social justice and well-being; charismatic power(s) of monastic practitioners, and more recently on Buddhist orthodoxy and how heretical monks are created in Myanmar.
- Contact: [[mailto:h.kawanami@lancaster.ac.uk][h.kawanami@lancaster.ac.uk]]
*** Courses
 - Note: Buddhist Studies is currently undergoing structural changes at the Department of Politics, Philosophy and Religion.
**** Undergraduate
- /The Power of the Past: Religion and Politics in South Asia/ (Bihani Sarkar)
- /Indian Religious and Philosophical Thought/ (Ram-Prasad or Brian Black) 
- /Buddhism, State and Political Monks/  (Hiroko Kawanami)

** The Courtauld Institute of Art
*** People
**** Lori Wong, Robert H. N. Ho Family Foundation Senior Lecturer in Conservation
- Research: Dunhuang conservation; conservation histories, practice and theory.
- Contact: [[mailto:lori.wong@courtauld.ac.uk][lori.wong@courtauld.ac.uk]]

**** Dr Sujatha Arundathi Meegama, Robert H. N. Ho Family Foundation Senior Lecturer in Buddhist Art History
- Research: Sri Lankan ivories made for the consumption of Portuguese, Dutch, British, and Sri Lankan Buddhist patrons; temple museums in Sri Lanka; informal shrines in modern-day Sri Lanka and Singapore; collecting and curating religious objects; and repatriation of Sri Lankan religious objects.
- Contact: [[mailto:sujatha.meegama@courtauld.ac.uk][sujatha.meegama@courtauld.ac.uk]]

*** Courses
**** MA Art History and Conservation of Buddhist Heritage
- [[https://courtauld.ac.uk/study/postgraduate/ma-buddhist-art-history-conservation/][Link to prospectus]].

** University College London
*** People 
**** [[https://www.ucl.ac.uk/anthropology/ucl-anthropology][Department of Anthropology]]
***** Dr Joanna Cook, Reader in Medical Anthropology
- Research: Buddhism, mental health, mindfulness; monasticism, gender (Thailand, UK); the anthropology of ethics. 
- Contact: [[mailto:joanna.cook@ucl.ac.uk][joanna.cook@ucl.ac.uk]]
** University of Aberdeen
*** People
**** [[https://www.abdn.ac.uk/socsci/][School of Social Science]]
***** Dr Martin A. Mills, Senior Lecturer
- Research: The anthropology of Tibet and Tibetan-speaking areas, and in particular its religious and state life (including the ceremonial nexuses of Tibetan monastic and state life); the formulation of new ways in which modern ethnographers of Tibetan regions can integrate their work with textual specialists and indigenous scholars to create an historical anthropology of the region.
- Contact: [[mailto:m.a.mills@abdn.ac.uk][m.a.mills@abdn.ac.uk]]
** University of Bristol
*** People
**** [[http://www.bristol.ac.uk/religion/][Department of Religion and Theology]]
***** Dr Benedetta Lomi, Lecturer in East Asian Religions
- Research: The History of Japanese Buddhism; Japanese Esoteric Buddhism; Esoteric Buddhism in East Asia, Buddhist Medicine, Healing Rituals, Buddhist Iconography.
- Contact: [[mailto:b.lomi@bristol.ac.uk][b.lomi@bristol.ac.uk]]
***** Dr Rita Langer, Senior Lecturer in Buddhist Studies
- Research: Merit in the early Pali sources; Buddhist ritual and its origin (in South and South East Asia, particularly Sri Lanka); Food and Cosmology).
- Contact: [[mailto:rita.langer@bristol.ac.uk][rita.langer@bristol.ac.uk]]
***** Dr Yael Shiri, Lecturer in Religious Studies
- Research: History of ancient Indian Buddhism; Indian religious narratives, both literary and visual, and their function as a vehicle for ideas, a tool for religious agency, identity formation, and religious polemics; Philological, narratological and art historical methods. Source materials covering Sanskrit, Classical Tibetan and Pāli.
- Contact: [[mailto:y.shiri@bristol.ac.uk][y.shiri@bristol.ac.uk]]
*** Courses
**** BA and MA in Religion and Theology [Not all these units will be available in any one year]:
- /Living Religions East/
- /Religions and Cultural Change in India: from Indus to Islam/
- /Religion and Material Culture/
- /Buddhism in Practice/
- /Buddhism: the Foundations/
- /Asian Traditions of Meditation/
- /The Many Faces of the Buddha: Literature, Archaeology and Visual Culture/
- /Sex, Humour, and Piety: Life in the ancient Buddhist Monastery/
- /Zen Buddhism/
- /Japanese Religions/
- /Chinese Religions/
- /Esoteric Buddhism in East Asia/
- /Mahāyāna Literature in East Asia/
- /The Body in East Asian Thought and Practices/
- /Sanskrit/
**** Religion and Theology research programmes (MPhil, PhD) 
- We welcome and encourage applications for postgraduate degrees by research in the area of Buddhist Studies. Our Mphil degree offers both a clear pathway to further research at PhD level, and a gateway to non-academic employment. The Master’s in Philosophy is a standalone, one-year (full-time) or two years (part-time) research degree and can also be studied via distance learning.

** University of Cambridge
- Note: As of the date of this posting, Buddhist Studies at the University of Cambridge is undergoing changes in personnel, and currently support for graduate Buddhist Studies is limited.
*** People
**** [[https://www.divinity.cam.ac.uk/][Faculty of Divinity]]
***** Dr Christopher V Jones, Research Associate and Affiliated Lecturer
- Research: Indian 'Buddha-nature' tradition as it has been preserved in South, Central and East Asian literatures, foremost in connection to literature associated with the /Mahāparinirvāṇa-mahāsūtra/Dabanniepan jing/; Pre-modern Buddhist attitudes to non-Buddhist teaching and authority in India and elsewhere, and the evolving place of Buddhist reflection on liberation and liberated beings in South Asia in the early centuries CE.
- Contact: [[mailto:cvj20@cam.ac.uk][cvj20@cam.ac.uk]]
**** [[https://www.ames.cam.ac.uk/][Faculty of Asian and Middle Eastern Studies]]
***** Professor Imre Galambos
- Research: Medieval China; Dunhuang studies; history of Chinese writing; Chinese manuscripts and epigraphy; contacts between China and Central Asia; Tangut studies; history of the exploration of Central Asia.
- Contact: [[mailto:iig21@cam.ac.uk][iig21@cam.ac.uk]]
** University of Chester
*** People
**** [[https://www1.chester.ac.uk/departments/theology-and-religious-studies][Department of Theology and Religious Studies: Faculty of Arts and Humanities]]
***** Dr Wendy Dossett, Associate Professor of Religious Studies
- Research: Japanese Pure Land Buddhism; Buddhism and Addiction Recovery; Buddhism and Religious Education.
- Contact: [[mailto:w.dossett@chester.ac.uk][w.dossett@chester.ac.uk]]
*** Courses
**** Undergraduate
 - /Dharmic Worldviews/ (Four sessions on Buddhism).
 - /Contemporary Asian Traditions/ (Four sessions on Buddhism).
**** Postgraduate
  - /Buddhist Concepts of Awakening/ (20 credit MA module in MA Theology and Religious Studies programme).
** University of Edinburgh
*** Note
- Prospective students are encouraged to get in touch via the Edinburgh Buddhist Studies (EBS) Network: [[mailto:buddhist.studies@ed.ac.uk][buddhist.studies@ed.ac.uk]].
*** People
**** [[https://www.ed.ac.uk/arts-humanities-soc-sci][College of Arts, Humanities and Social Sciences]]
***** Dr Halle O’Neal, Reader in Japanese Art
 - Note: On research leave.
 - Research: Japanese Buddhist art; Word and image studies; Relics and reliquaries; Performativity and haptic nature of manuscripts; Death commemorations in visual and material culture; Palimpsests; Digital Humanities.
 - Contact: [[mailto:halle.oneal@ed.ac.uk][halle.oneal@ed.ac.uk]]
***** Dr Ian Astley, Senior Lecturer in Japanese
 - Research: Japanese and Chinese religions and philosophy, especially Shingon Buddhist tradition in China and Japan, focussing on the development of the school's thought in the transition from a Chinese to a Japanese religio-political environment, with particular reference to the role of material culture and prosody in the development of ideology in the body politic; The early commentarial tradition of the Liqu jing (J.: Rishukyō); Developments in the Meiji Restoration, with particular reference to Shingon Buddhism and the manner in which the Japanese were introducing their form of Buddhism to the West, more specifically the UK.
 - Contact: [[mailto:ian.astley@ed.ac.uk][ian.astley@ed.ac.uk]]
***** Dr Naomi Appleton, Senior Lecturer in Asian Religions
 - Research: Early Indian religions (Hinduism, Buddhism, Jainism) and Buddhist Studies more broadly; Role of narrative in the construction, communication and negotiation of ideas in Indian religions, including Buddhism, Jainism and early Hindu traditions.
 - Contact: [[mailto:naomi.appleton@ed.ac.uk][naomi.appleton@ed.ac.uk]]
***** Prof Joachim Gentz, Chair in Chinese Philosophy and Religion
 - Research: Chinese philosophy and religions, text and commentary, ritual and divination, and theories of cultural and religious; Conceptions of space and body; Chinese histories of thought, and Chinese literary composition (artistic prose).
 - Contact: [[mailto:joachim.gentz@ed.ac.uk][joachim.gentz@ed.ac.uk]]
***** Dr Paul Fuller, Teaching Fellow in Buddhist Studies
- Research: Textual basis of discrimination and attachment in early Buddhism; Engaged Buddhism; The prevalence of blasphemy in Buddhist culture; Political and chauvinistic expressions of Buddhism; Contemporary issues in Buddhism including, politics, sexuality, gender, eco-engaged Buddhism and ethnocentric Buddhism.
- Contact: [[mailto:paul.fuller@ed.ac.uk][paul.fuller@ed.ac.uk]]
***** Dr Takeshi Morisato 森里武, Lecturer 
- Research: Metaphysics, Philosophy of Religion, and Existentialism; Contemporary Japanese philosophy (especially the Kyoto School); Kūkai 空海 (774–835) and his Shingon Esoteric Buddhist philosophy.
- Contact: [[mailto:tmorisat@ed.ac.uk][tmorisat@ed.ac.uk]]
***** Prof Jonathan Spencer, Regius Professor of South Asian Language, Culture and Society 
 - Research: Religion and politics; Sri Lanka; South and Southeast Asia; Buddhism; war and peace.
 - Contact: [[mailto:jonathan.spencer@ed.ac.uk][jonathan.spencer@ed.ac.uk]]
***** Dr Abigail MacBain, Lecturer of Premodern Japanese Studies
- Research: Buddhism's transmission to Japan and its role in early Japan's overseas relations; Overlap between Buddhism and the state, and Japan's role in Silk Road trade and communication. 
- Contact: [[mailto:abigail.macbain@ed.ac.uk][abigail.macbain@ed.ac.uk]]
*** Courses
   - MA Religious Studies (4 year undergraduate programme, School of Divinity).
   - MA Chinese and MA Japanese (4 year undergraduate programmes, Asian Studies).
   - Anthropology, Art History and Philosophy also have some relevant optional courses.
   - Courses on offer vary year on year, and are often available across programmes outside their “home” School.
   - At postgraduate level there is a taught masters (MSc) in Religious Studies, and research degrees (MScR, PhD) available working with any of the people noted above.
     - Note: Please contact individual members of staff to discuss this.
** University of Kent
*** People
**** [[https://www.kent.ac.uk/religious-studies/][Department of Religious Studies]]
***** Dr Leslie De Vries, Lecturer in East Asian Studies
- Research: History of medicine and religion in China, Vietnam and Japan, with a focus on cosmology, the body, self-cultivation and therapy.
- Contact: [[mailto:l.devries@kent.ac.uk][l.devries@kent.ac.uk]]
*** Courses
**** Undergraduate
- /Introduction to Hinduism and Buddhism/
- /Religion and Japanese Culture/
- /Health, Medicine and the Body in East Asia/
 
** University of Leeds
*** People
**** [[https://ahc.leeds.ac.uk/languages][School of Languages, Cultures and Societies]]
***** Professor Martin Seeger, Professor of Thai Studies
- Research: Theravada Buddhism; Thai Buddhism; modern Thai history; Thai language. 
- Contact: [[mailto:m.seeger@leeds.ac.uk][m.seeger@leeds.ac.uk]]
** University of London, School of Oriental and African Studies (SOAS) 
*** People
**** [[https://www.soas.ac.uk/about/schools-departments-and-sections/department-religions-and-philosophies][Department of Religions and Philosophies]]
***** Dr Lucia Dolce, Numata Reader in Japanese Buddhism
- Research: Japanese religious history, especially the medieval period; Japanese Tantric Buddhism and the esotericisation of religious practice; Millenarian writings and prophecy; Kami-Buddhas associations
- Contact: [[mailto:ld16@soas.ac.uk][ld16@soas.ac.uk]]
***** Professor Ulrich Pagel, Head of School
- Research: History of Buddhism in Tibet, Mahāyāna Buddhism, Kanjur Studies, Vinaya, Religions of Central Asia, Tibetan, Sanskrit. 
- Contact: [[mailto:up1@soas.ac.uk][up1@soas.ac.uk]]
**** [[https://www.soas.ac.uk/about/schools-departments-and-sections/department-history-art-and-archaeology][Department of the History of Art and Archaeology]]
***** Dr Christian Luczanits, David L. Snellgrove Senior Lecturer in Tibetan and Buddhist Art
- Research: History of art and architecture of the Himalayan region; Buddhist art of the western Himalayas; Gandharan art; presenting and exhibiting Buddhist art; heritage, preservation and conservation.
- Contact: [[mailto:cl46@soas.ac.uk][cl46@soas.ac.uk]]
***** Dr Peter D. Sharrock, Senior Teaching Fellow
- Research: He is now focusing on the evidence in Indochina for the influence of tantric or esoteric Buddhism, developed in the great monasteries of the Ganges valley and diffused and developed in different ways through much of Asia. 
- Contact: [[mailto:ps56@soas.ac.uk][ps56@soas.ac.uk]]
*** Courses
**** Postgraduate
- MA Buddhist Studies
** University of Manchester
*** People
**** [[https://www.research.manchester.ac.uk/portal/en/facultiesandschools/school-of-arts-languages-and-cultures(67be616e-b627-4747-a791-872e7594dfc1).html][School of Arts, Languages and Cultures]]
***** Dr Gregory Adam Scott, Senior Lecturer in Chinese Culture and History
- Research: History and culture of China between 1800 and 1978. 
- Contact: [[mailto:gregory.scott@manchester.ac.uk][gregory.scott@manchester.ac.uk]]
***** Prof Erica Baffelli, Professor of Japanese Studies
- Research: Religion in contemporary Japan with a focus on religious minorities/marginalities, media and technology, violence, emotions and temporalities. 
- Contact: [[mailto:erica.baffelli@manchester.ac.uk][erica.baffelli@manchester.ac.uk]]
*** Courses
- /History of Religion in Japan/
- /Ideas and Ideologies in Chinese Civilisation/
** University of Oxford
*** People
**** [[https://orinst.web.ox.ac.uk/][Faculty of Asian and Middle Eastern Studies]]
***** Dr Cathy Cantwell, Associate Faculty Member
- Research: Tibetan textual transmission/development; tantric rituals, symbolism, art; rNying-ma canonical texts; Dunhuang and later ritual manuals; Phur-pa traditions (rNying-ma, Sa-skya, Bon); bDud-’joms gter-ma tradition.
- Contact: [[mailto:catherine.cantwell@orinst.ox.ac.uk][catherine.cantwell@orinst.ox.ac.uk]]
***** Dr Robert Mayer, University Research Lecturer
- Research: Early rNying ma and Bon tantric tradition; Critically editing old Tibetan texts; Dunhuang tantric texts.
- Contact: [[mailto:robert.mayer@orinst.ox.ac.uk][robert.mayer@orinst.ox.ac.uk]]
***** Dr Sarah Shaw, Faculty Member
- Research: Early Buddhist (Pali) suttas and Abhidhamma material on meditation; Early Buddhist narrative: literary features of Jatakas and Dhammapada stories; Indian and Asian influences on British nineteenth-century writers; modern South and Southeast Asian Buddhist ritual, chant and meditation.
- Contact: [[mailto:sarah.shaw@orinst.ox.ac.uk][sarah.shaw@orinst.ox.ac.uk]]
***** Prof David Gellner, Professor of Social Anthropology
- Research: Anthropology of South Asia; East Asia; Buddhism; Hinduism; cities;ritual; politics; ethnicity; activism; borderlands; class formation and cultural change.
- Contact: [[mailto:david.gellner@anthro.ox.ac.uk][david.gellner@anthro.ox.ac.uk]]
***** Prof Kate Crosby, Numata Professor of Buddhist Studies
- Research: Pali; Sanskrit; and Sri Lanka and Southeast Asia literature; Theravada meditation; history and practice; comparative Theravada.
- Contact: [[mailto:kate.crosby@orinst.ox.ac.uk][kate.crosby@orinst.ox.ac.uk]]
***** Prof Ulrike Roesler, Professor of Tibetan and Himalayan Studies
- Research: Literature and religion of the Veda; Indo-Tibetan Buddhism; history of bKa’-gdams-pa school; ‘sacred landscapes’ in literature and ritual practice.
- Contact: [[mailto:ulrike.roesler@orinst.ox.ac.uk][ulrike.roesler@orinst.ox.ac.uk]]
**** [[https://www.theology.ox.ac.uk/][Faculty of Theology and Religion]]
***** Dr Andrew Skilton, Pali Instructor
- Research: Colllecting, interpretation and translation of Buddhist texts; the roles of writing and orality in the formation of Buddhist scripture; pre-reform meditation systems in the Theravada Buddhist world, and Buddhist meditation in general; Mahayana scripture, especially the Samadhiraja Sutra (C2nd CE); Buddhism in the contemporary world, including its transmission to the UK.
- Contact: [[mailto:andrew.skilton@theology.ox.ac.uk][andrew.skilton@theology.ox.ac.uk]]
***** Prof Jan Westerhoff, Professor of Buddhist Philosophy
- Research: Philosophical aspects of the religious traditions of ancient India. Buddhist thought (especially Madhyamaka) as preserved in Sanskrit and Tibetan sources; Classical Indian philosophy (particularly Nyāya); Buddhist philosophy, both theoretical (metaphysics, epistemology, philosophy of language) and normative aspects (ethics).
- Contact: [[mailto:jan.westerhoff@theology.ox.ac.uk][jan.westerhoff@theology.ox.ac.uk]]
*** Courses
**** Undergraduate
 - BA Religion and Asian and Middle Eastern Studies
 - BA in Sanskrit:
**** Postgraduate
 - MSt in Asian and Middle Eastern Studies
 - MPhil in Buddhist Studies
 - MPhil in Classical Indian Religion
 - MPhil in Tibetan and Himalayan Studies
** University of South Wales
*** People
**** [[https://www.southwales.ac.uk/courses/faculty/FCI/?faculty_title=Faculty+of+Creative+Industries][Faculty of Creative Industries]]
***** Dr Nick Swann, Senior Lecturer and Course Leader
- Research: Tibetan Religion; Anthropology of Religion; Buddhist Ethics; Digital Buddhism.
- Contact: [[mailto:nick.swann@southwales.ac.uk][nick.swann@southwales.ac.uk]]
***** Dr Sarah Shaw, Khyentse Foundation Reader in Buddhist Studies
- Research: Pāli Buddhist narrative and meditative literature; Southeast Asian ritual and chant; Abhidhamma.
- Contact: [[mailto:sarah.shaw@southwales.ac.uk][sarah.shaw@southwales.ac.uk]]
***** Dr Warren Todd, Visiting Lecturer in Buddhist Studies
- Research: Buddhist Philosophy; Buddhist Ethics; Comparative Ethics & Philosophy.
- Contact: [[mailto:warren.todd@southwales.ac.uk][warren.todd@southwales.ac.uk]]
*** Courses
**** Postgraduate
- MA Buddhist Studies (Part-time distance learning)
  - /Buddhist Traditions/
  - /Buddhist Meditation and Psychology/
  - /Buddhist Ethics/
  - /Buddhist Philosophy/
  - /Pali Language/
  - /Dissertation in Buddhist Studies/
** University of Stirling
*** People
**** [[https://www.stir.ac.uk/about/faculties/arts-humanities/literature-and-languages/][Division of Literature and Languages]]
***** Mr Kevin MacNeil, Lecturer in Creative Writing
- Research: The intersection of Buddhism and literature, recent and contemporary literature of the Scottish Highlands and Islands; Buddhism (Theravada and Mahayana, but especially interested in Zen); Scottish Literature, poetry and prose of the Hebrides; contemporary novels; creative writing; playwriting; screenwriting; poetry; Buddhist literature; the connections between physical activity and creativity.
- Contact: [[mailto:kevin.macneil@stir.ac.uk][kevin.macneil@stir.ac.uk]]
** University of Winchester
*** People
**** [[https://www.winchester.ac.uk/research/our-impactful-research/research-in-humanities-and-social-sciences/research-centres-and-networks/centre-for-religion-reconciliation-and-peace/][Centre for Religion, Reconciliation and Peace]]
***** Professor Anna King
- Research: The theoretical study of the interrelation between religion and politics/nationalism; Religion, conflict, and peacebuilding; Multiculturalism as a framework for conflict transformation and as a theory of justice; The role of religious leaders, narratives and communities in re-imagining questions of peace and justice; The role of interfaith dialogue in ethno-religious national contexts; The theorisation of ‘religion’ and ‘spirituality’ in a globalising world; Contemporary Buddhist and Hindu schools and traditions and their engagement with shared global challenges (global warming, environmental degradation, advances in genetics and neuroscience, animal welfare and rights, etc.).
- Contact: [[mailto:anna.king@winchester.ac.uk][anna.king@winchester.ac.uk]]
***** Professor Mark Owen, Director: Centre for Religion, Reconciliation and Peace
- Research: Religions' role in peacebuilding and conflict transformation; conflict assessment and analysis; Buddhism, conflict and peacebuilding; Tibetan Buddhism; Asian politics and development.
- Contact: [[mailto:mark.owen@winchester.ac.uk][mark.owen@winchester.ac.uk]]
